### ISSUE TITLE
Unable to visualize OSI Data

### ISSUE THREAD

**Issue by Alex7-K** [Lichtblick-Suite/asam-osi-converter#19]
I installed Lichtblick and the osi-converter extension and loaded the example osi mcap file "only_osi_topic.mcap".
I am able to see the OSI structure in the rawdata panel but nothing in the 3D Panel. 
Am i missing a step here? 
Tried it on both Windows and Ubuntu 20.4, with the example file and an osi.txt->osi.mcap converted file.

![LichtblickOsi](https://github.com/user-attachments/assets/cac05f83-87ef-4656-ac14-c99a54381ab0)

**Comment by jdsika** [comment]
You cought me in between transition. I will upload example files this week. Here a readme how you can create you own:

https://github.com/Lichtblick-Suite/asam-osi-converter/pull/20

**Comment by thomassedlmayer** [comment]
@Alex7-K Looks like the topic is missing in your screenshot. Does the extension show up in the list of installed extensions for you? After I install the asam-osi-converter extension, I can see the topic and if I click on the eye-button I can see the visualization. Without the extension, I can also only see the OSI raw structure and no topic appears.

![image](https://github.com/user-attachments/assets/6f4805f9-44be-404e-8c68-845c4c984e97)

But maybe, as @jdsika said, there could also be an issue with the structure of the mcap file. I don't know.

**Comment by jdsika** [comment]
The example trace has a "not OSI compliant" topic name. That's why the extension ignores it and does not connect to it

**Comment by Alex7-K** [comment]
Thanks for the support, we finaly found the issue. 
We had some empty static objects in our osi structure, resulting in Lichtblick to not visualize OSI data at all. 
![image](https://github.com/user-attachments/assets/7b60aa5c-a444-43ba-9662-413a46cc1904)

Working with Python we've created a small Osi Mcap converter(input: .osi, .txt), we can share it if you like.

**Comment by jdsika** [comment]
Ok, can you add the file as test case in an extra issue please?

It would be great if you would extend the c++ converter here with a python equivalent!

https://github.com/Lichtblick-Suite/asam-osi-utilities
